import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: "1",
    firstName: "Rajashree",
    lastName: "Parhi",
    username: "rajashree",
    password: "1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bio: "Carpe Diem",
    website: "rajashreeparhi.com",
    followers: [],
    following: [
      {
        _id: "5",
        firstName: "Monalisha",
        lastName: "Mishra",
        username: "monalisha",
        password: "1234",
        createdAt: "2023-06-29T18:58:30+05:30",
        updatedAt: "2023-06-29T18:58:30+05:30",
        followers: [],
        following: [],
        bookmarks: [],
        profileAvatar:
          "https://res.cloudinary.com/di7drmeev/image/upload/v1687962171/travelgram/profile-pictures/monalisha.jpg",
        id: "5",
      },
      {
        _id: "2",
        firstName: "Agni",
        lastName: "Panda",
        username: "agni",
        password: "1234",
        createdAt: "2023-06-29T18:58:30+05:30",
        updatedAt: "2023-06-29T19:00:49+05:30",
        followers: [],
        following: [],
        bookmarks: [],
        profileAvatar:
          "https://res.cloudinary.com/di7drmeev/image/upload/v1687962057/travelgram/profile-pictures/agni.jpg",
        id: "2",
      },
    ],
    bookmarks: [],
    profileAvatar:
      "https://res.cloudinary.com/di7drmeev/image/upload/v1687956260/travelgram/profile-pictures/rajashree.jpg",
  },
  {
    _id: "2",
    firstName: "Agni",
    lastName: "Panda",
    username: "agni",
    password: "1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [
      {
        _id: "1",
        firstName: "Rajashree",
        lastName: "Parhi",
        username: "rajashree",
        password: "1234",
        createdAt: formatDate(),
        updatedAt: formatDate(),
        followers: [],
        following: [
          {
            _id: "5",
            firstName: "Monalisha",
            lastName: "Mishra",
            username: "monalisha",
            password: "1234",
            createdAt: "2023-06-29T18:58:30+05:30",
            updatedAt: "2023-06-29T18:58:30+05:30",
            followers: [],
            following: [],
            bookmarks: [],
            profileAvatar:
              "https://res.cloudinary.com/di7drmeev/image/upload/v1687962171/travelgram/profile-pictures/monalisha.jpg",
            id: "5",
          },
          {
            _id: "2",
            firstName: "Agni",
            lastName: "Panda",
            username: "agni",
            password: "1234",
            createdAt: "2023-06-29T18:58:30+05:30",
            updatedAt: "2023-06-29T19:00:49+05:30",
            followers: [],
            following: [],
            bookmarks: [],
            profileAvatar:
              "https://res.cloudinary.com/di7drmeev/image/upload/v1687962057/travelgram/profile-pictures/agni.jpg",
            id: "2",
          },
        ],
        bookmarks: [],
        profileAvatar:
          "https://res.cloudinary.com/di7drmeev/image/upload/v1687956260/travelgram/profile-pictures/rajashree.jpg",
      },
    ],
    following: [],
    bookmarks: [],
    profileAvatar:
      "https://res.cloudinary.com/di7drmeev/image/upload/v1687962057/travelgram/profile-pictures/agni.jpg",
  },
  {
    _id: "3",
    firstName: "Arka",
    lastName: "Sengupta",
    username: "relentless23",
    password: "1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [],
    following: [],
    bookmarks: [],
    profileAvatar:
      "https://res.cloudinary.com/di7drmeev/image/upload/v1687962761/travelgram/profile-pictures/arka.jpg",
  },
  {
    _id: "4",
    firstName: "Tapaja",
    lastName: "Banerjee",
    username: "tapaja",
    password: "1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [],
    following: [],
    bookmarks: [],
    profileAvatar:
      "https://res.cloudinary.com/di7drmeev/image/upload/v1687962205/travelgram/profile-pictures/tapaja.jpg",
  },
  {
    _id: "5",
    firstName: "Monalisha",
    lastName: "Mishra",
    username: "monalisha",
    password: "1234",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [
      {
        _id: "1",
        firstName: "Rajashree",
        lastName: "Parhi",
        username: "rajashree",
        password: "1234",
        createdAt: formatDate(),
        updatedAt: formatDate(),
        followers: [],
        following: [
          {
            _id: "5",
            firstName: "Monalisha",
            lastName: "Mishra",
            username: "monalisha",
            password: "1234",
            createdAt: "2023-06-29T18:58:30+05:30",
            updatedAt: "2023-06-29T18:58:30+05:30",
            followers: [],
            following: [],
            bookmarks: [],
            profileAvatar:
              "https://res.cloudinary.com/di7drmeev/image/upload/v1687962171/travelgram/profile-pictures/monalisha.jpg",
            id: "5",
          },
          {
            _id: "2",
            firstName: "Agni",
            lastName: "Panda",
            username: "agni",
            password: "1234",
            createdAt: "2023-06-29T18:58:30+05:30",
            updatedAt: "2023-06-29T19:00:49+05:30",
            followers: [],
            following: [],
            bookmarks: [],
            profileAvatar:
              "https://res.cloudinary.com/di7drmeev/image/upload/v1687962057/travelgram/profile-pictures/agni.jpg",
            id: "2",
          },
        ],
        bookmarks: [],
        profileAvatar:
          "https://res.cloudinary.com/di7drmeev/image/upload/v1687956260/travelgram/profile-pictures/rajashree.jpg",
      },
    ],
    following: [],
    bookmarks: [],
    profileAvatar:
      "https://res.cloudinary.com/di7drmeev/image/upload/v1687962171/travelgram/profile-pictures/monalisha.jpg",
  },
];
