export const ACTION_TYPES = {
  SET_TOKEN: "SET_TOKEN",
  SET_AUTH_USER: "SET_AUTH_USER",
  SET_ALL_USERS: "SET_ALL_USERS",
  SET_BOOKMARKS:"SET_BOOKMARKS",
  LOG_OUT: "LOG_OUT",

  SET_POSTS: "SET_POSTS",
  SET_LOADER:"SET_LOADER",
};
